import { StateMaster, DistrictMaster, Project, Parcel, Village, FarmerRecord, Bottleneck, OfficerWorkloadRecord } from '../types';

const ts = Date.now();

export const FALLBACK_STATES: StateMaster[] = [
  { id: 'state-mh', name: 'Maharashtra', code: 'MH', totalDistricts: 36, activeProjectsCount: 14, createdAt: ts, updatedAt: ts },
  { id: 'state-gj', name: 'Gujarat', code: 'GJ', totalDistricts: 33, activeProjectsCount: 12, createdAt: ts, updatedAt: ts },
  { id: 'state-up', name: 'Uttar Pradesh', code: 'UP', totalDistricts: 75, activeProjectsCount: 28, createdAt: ts, updatedAt: ts },
  { id: 'state-rj', name: 'Rajasthan', code: 'RJ', totalDistricts: 50, activeProjectsCount: 9, createdAt: ts, updatedAt: ts },
];

export const FALLBACK_DISTRICTS: DistrictMaster[] = [
  { id: 'dist-palghar', stateId: 'state-mh', name: 'Palghar', code: 'PLG', headquarters: 'Palghar', createdAt: ts, updatedAt: ts },
  { id: 'dist-thane', stateId: 'state-mh', name: 'Thane', code: 'THN', headquarters: 'Thane City', createdAt: ts, updatedAt: ts },
  { id: 'dist-ahmedabad', stateId: 'state-gj', name: 'Ahmedabad', code: 'AHM', headquarters: 'Ahmedabad', createdAt: ts, updatedAt: ts },
  { id: 'dist-surat', stateId: 'state-gj', name: 'Surat', code: 'SRT', headquarters: 'Surat', createdAt: ts, updatedAt: ts },
  { id: 'dist-varanasi', stateId: 'state-up', name: 'Varanasi', code: 'VNS', headquarters: 'Varanasi', createdAt: ts, updatedAt: ts },
];

export const FALLBACK_PROJECTS: Project[] = [
  {
    id: 'proj-bullet-train-sec-3',
    name: 'Mumbai-Ahmedabad High Speed Rail (Package C3)',
    code: 'MAHSR-PKG-C3',
    stateId: 'state-mh',
    districtIds: ['dist-palghar', 'dist-thane', 'dist-surat'],
    departmentId: 'dept-nhsrcl',
    description: 'Acquisition of 184.6 hectares for High Speed Rail Viaduct.',
    totalAreaRequiredAcres: 456.2,
    totalBudgetINR: 145000000000,
    currentStage: 'Sec_19_Declaration',
    startDate: '2025-01-15',
    targetCompletionDate: '2027-06-30',
    status: 'ACTIVE',
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: 'proj-delhi-mumbai-expressway-p4',
    name: 'Delhi-Mumbai Expressway (Phase 4 Package)',
    code: 'DME-PH4-PKG12',
    stateId: 'state-gj',
    districtIds: ['dist-surat', 'dist-palghar'],
    departmentId: 'dept-nhai',
    description: '8-Lane Access Controlled Greenfield Expressway Corridor.',
    totalAreaRequiredAcres: 612.0,
    totalBudgetINR: 88000000000,
    currentStage: 'Possession',
    startDate: '2024-06-01',
    targetCompletionDate: '2026-12-31',
    status: 'ACTIVE',
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: 'proj-solapur-tuljapur-rail',
    name: 'Solapur-Tuljapur-Chhatrapati Sambhajinagar Rail Corridor',
    code: 'CR-STC-RAIL-2026',
    stateId: 'state-mh',
    districtIds: ['dist-solapur', 'dist-[#D97706]'],
    departmentId: 'dept-ir',
    description: 'New Railway Corridor Connecting Pilgrimage & Industrial Hubs with Mountain Tunneling.',
    totalAreaRequiredAcres: 340.5,
    totalBudgetINR: 32000000000,
    currentStage: 'Sec_19_Declaration',
    startDate: '2025-03-01',
    targetCompletionDate: '2028-03-31',
    status: 'ACTIVE',
    createdAt: ts,
    updatedAt: ts,
  }
];

export const FALLBACK_VILLAGES: Village[] = [
  { id: 'vill-manikpur', projectId: 'proj-bullet-train-sec-3', name: 'Manikpur', censusCode: '27-PLG-001', districtId: 'dist-palghar', totalParcelsCount: 24, createdAt: ts, updatedAt: ts },
  { id: 'vill-kelve', projectId: 'proj-bullet-train-sec-3', name: 'Kelve', censusCode: '27-PLG-002', districtId: 'dist-palghar', totalParcelsCount: 18, createdAt: ts, updatedAt: ts },
  { id: 'vill-sachin', projectId: 'proj-bullet-train-sec-3', name: 'Sachin', censusCode: '24-SRT-001', districtId: 'dist-surat', totalParcelsCount: 31, createdAt: ts, updatedAt: ts },
  { id: 'vill-[#D97706]', projectId: 'proj-solapur-tuljapur-rail', name: 'Tuljapur Rural', censusCode: '27-TLJ-001', districtId: 'dist-[#D97706]', totalParcelsCount: 42, createdAt: ts, updatedAt: ts },
];

export const FALLBACK_PARCELS: Parcel[] = [
  {
    id: 'parcel-palghar-0142',
    projectId: 'proj-bullet-train-sec-3',
    villageId: 'vill-manikpur',
    khasraSurveyNo: '401/P-AHM',
    ulpin: 'ULPIN-MH-142A1-2026',
    areaAcres: 6.2,
    landClassification: 'Commercial',
    status: 'AWARDED',
    estimatedMarketValueINR: 52000000,
    calculatedSolatiumINR: 52000000,
    totalCompensationINR: 104000000,
    geoCenter: { lat: 19.6967, lng: 72.7699 },
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: 'parcel-palghar-0143',
    projectId: 'proj-bullet-train-sec-3',
    villageId: 'vill-kelve',
    khasraSurveyNo: '12/A-BKC',
    ulpin: 'ULPIN-MH-1432B-2026',
    areaAcres: 3.8,
    landClassification: 'Commercial',
    status: 'AWARDED',
    estimatedMarketValueINR: 52800000,
    calculatedSolatiumINR: 52800000,
    totalCompensationINR: 105600000,
    geoCenter: { lat: 19.6201, lng: 72.7405 },
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: 'parcel-surat-0204',
    projectId: 'proj-bullet-train-sec-3',
    villageId: 'vill-sachin',
    khasraSurveyNo: '142/A-1',
    ulpin: 'ULPIN-GJ-2041A-2026',
    areaAcres: 2.45,
    landClassification: 'Agricultural',
    status: 'AWARDED',
    estimatedMarketValueINR: 13750000,
    calculatedSolatiumINR: 13750000,
    totalCompensationINR: 27500000,
    geoCenter: { lat: 21.1700, lng: 72.8320 },
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: 'parcel-surat-0312',
    projectId: 'proj-delhi-mumbai-expressway-p4',
    villageId: 'vill-sachin',
    khasraSurveyNo: '143/2-B',
    ulpin: 'ULPIN-GJ-3121V-2026',
    areaAcres: 1.15,
    landClassification: 'Residential',
    status: 'NOTIFIED',
    estimatedMarketValueINR: 9790000,
    calculatedSolatiumINR: 9790000,
    totalCompensationINR: 19580000,
    geoCenter: { lat: 21.1725, lng: 72.8350 },
    createdAt: ts,
    updatedAt: ts,
  }
];

export const FALLBACK_FARMERS: FarmerRecord[] = [
  {
    id: 'farmer-palghar-001',
    farmerName: 'Shri Dattatray B. Patil',
    contactNumber: '+91 98231 44521',
    aadhaarMasked: 'XXXX-XXXX-8821',
    state: 'Maharashtra',
    district: 'Palghar',
    talukaTehsil: 'Palghar',
    village: 'Manikpur',
    khataNumber: 'Khata-892',
    surveyGatNumber: '142/A-1',
    hissaNumber: 'Hissa-1',
    ulpin: 'ULPIN-MH-142A1-2026',
    totalLandAreaAcres: 3.45,
    acquiredAreaAcres: 2.45,
    retainedAreaAcres: 1.00,
    landClassification: 'Agricultural',
    soilType: 'Alluvial Loam Coastal Plain',
    tenureType: 'Occupant Class I (Freehold Khatedar)',
    jointHolders: [
      { name: 'Smt. Anusaya D. Patil', shareFraction: '1/2', relation: 'Wife' },
      { name: 'Shri Rajesh D. Patil', shareFraction: '1/2', relation: 'Son' }
    ],
    estimatedValuationINR: 13750000,
    solatiumINR: 13750000,
    totalCompensationINR: 27500000,
    disbursementStatus: 'DISBURSED',
    bankDetails: { bankName: 'State Bank of India (Palghar Branch)', accountMasked: 'XXXXXX4092', ifsc: 'SBIN0001244' },
    dgpsPillars: [{ pillarId: 'PIL-142-NW', lat: 19.6975, lng: 72.7690, rtkAccuracyCm: 1.4 }],
    boundaryPolygon: [{ lat: 19.6975, lng: 72.7690 }],
    qrPasscode: 'QR-KS-MH-142A1',
    arVerificationStatus: 'VERIFIED',
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: 'farmer-kanpur-009',
    farmerName: 'Shri Suresh Chandra Verma',
    contactNumber: '+91 94150 99412',
    aadhaarMasked: 'XXXX-XXXX-5561',
    state: 'Uttar Pradesh',
    district: 'Kanpur Nagar',
    talukaTehsil: 'Bilhaur',
    village: 'Araul',
    khataNumber: 'Khata-817',
    surveyGatNumber: '712/4',
    hissaNumber: 'Hissa-4',
    ulpin: 'ULPIN-UP-7124K-2026',
    totalLandAreaAcres: 5.60,
    acquiredAreaAcres: 5.60,
    retainedAreaAcres: 0.00,
    landClassification: 'Commercial',
    soilType: 'Heavy Alluvial Plain',
    tenureType: 'Bhumidhar with Transferable Rights',
    jointHolders: [{ name: 'Smt. Shanti Devi Verma', shareFraction: '1/1', relation: 'Wife' }],
    estimatedValuationINR: 35200000,
    solatiumINR: 35200000,
    totalCompensationINR: 70400000,
    disbursementStatus: 'IN_PROGRESS',
    bankDetails: { bankName: 'Canara Bank (Mall Road Kanpur)', accountMasked: 'XXXXXX1248', ifsc: 'CNRB0000219' },
    dgpsPillars: [{ pillarId: 'PIL-KNP-01', lat: 26.4515, lng: 80.3300, rtkAccuracyCm: 1.4 }],
    boundaryPolygon: [{ lat: 26.4515, lng: 80.3300 }],
    qrPasscode: 'QR-KS-UP-7124K',
    arVerificationStatus: 'VERIFIED',
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: 'farmer-jaipur-004',
    farmerName: 'Shri Jagdishprasad R. Sharma',
    contactNumber: '+91 94140 22891',
    aadhaarMasked: 'XXXX-XXXX-6612',
    state: 'Rajasthan',
    district: 'Jaipur',
    talukaTehsil: 'Bassi',
    village: 'Bassi Rural',
    khataNumber: 'Khata-771',
    surveyGatNumber: '119/2',
    hissaNumber: 'Hissa-3',
    ulpin: 'ULPIN-RJ-1192J-2026',
    totalLandAreaAcres: 6.20,
    acquiredAreaAcres: 5.10,
    retainedAreaAcres: 1.10,
    landClassification: 'Agricultural',
    soilType: 'Sandy Loam Semiarid Soil',
    tenureType: 'Khatedar Tenant (Permanent)',
    jointHolders: [{ name: 'Shri Rameshwarlal Sharma', shareFraction: '1/2', relation: 'Brother' }],
    estimatedValuationINR: 20900000,
    solatiumINR: 20900000,
    totalCompensationINR: 41800000,
    disbursementStatus: 'DISBURSED',
    bankDetails: { bankName: 'Punjab National Bank (Jaipur Bassi)', accountMasked: 'XXXXXX1902', ifsc: 'PUNB0021900' },
    dgpsPillars: [{ pillarId: 'PIL-BAS-01', lat: 26.8320, lng: 76.0410, rtkAccuracyCm: 1.2 }],
    boundaryPolygon: [{ lat: 26.8320, lng: 76.0410 }],
    qrPasscode: 'QR-KS-RJ-1192J',
    arVerificationStatus: 'VERIFIED',
    createdAt: ts,
    updatedAt: ts,
  }
];

export const FALLBACK_BOTTLENECKS: Bottleneck[] = [
  {
    id: 'bot-palghar-title-dispute',
    projectId: 'proj-bullet-train-sec-3',
    title: '3-Party Succession Title Litigation in Palghar',
    rootCause: 'COURT_STAY',
    severity: 'CRITICAL',
    delayDaysEstimated: 45,
    status: 'IDENTIFIED',
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: 'bot-surat-nhai-noc',
    projectId: 'proj-delhi-mumbai-expressway-p4',
    title: 'NHAI Highway Crossing Utility NOC Delay',
    rootCause: 'INTER_DEPARTMENTAL_NOC',
    severity: 'HIGH',
    delayDaysEstimated: 30,
    status: 'IDENTIFIED',
    createdAt: ts,
    updatedAt: ts,
  }
];

export const FALLBACK_OFFICER_WORKLOADS: OfficerWorkloadRecord[] = [
  {
    id: 'workload-01',
    officerUid: 'off-mh-palghar-01',
    officerName: 'Shri Vikram Joshi, IAS',
    role: 'FIELD_ACQUISITION',
    districtId: 'dist-palghar',
    stateId: 'state-mh',
    assignedCases: 18,
    pendingCases: 7,
    completedCases: 11,
    overdueCases: 3,
    averageResolutionDays: 14,
    maxCapacity: 20,
    complexityScore: 4,
    calculatedWorkloadScore: 86.4,
    isAvailable: true,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: 'workload-02',
    officerUid: 'off-gj-surat-02',
    officerName: 'Er. Rajesh Kulkarni',
    role: 'FIELD_ACQUISITION',
    districtId: 'dist-surat',
    stateId: 'state-gj',
    assignedCases: 12,
    pendingCases: 3,
    completedCases: 9,
    overdueCases: 1,
    averageResolutionDays: 10,
    maxCapacity: 25,
    complexityScore: 3,
    calculatedWorkloadScore: 52.0,
    isAvailable: true,
    createdAt: ts,
    updatedAt: ts,
  },
];
