import { initializeApp } from 'firebase/app';
import { getFirestore, doc, setDoc } from 'firebase/firestore';

const firebaseConfig = {
  apiKey: "AIzaSyAEZ6Tiz3-6xZRAiBXj99dFgSxDGhXGDSw",
  authDomain: "dataaq-69662.firebaseapp.com",
  projectId: "dataaq-69662",
  storageBucket: "dataaq-69662.firebasestorage.app",
  messagingSenderId: "740135530786",
  appId: "1:740135530786:web:e06c73696ce34abc92f57b",
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

const farmers = [
  {
    id: 'farmer-palghar-001',
    farmerName: 'Shri Dattatray B. Patil',
    contactNumber: '+91 98231 44521',
    aadhaarMasked: 'XXXX-XXXX-8821',
    state: 'Maharashtra',
    district: 'Palghar',
    talukaTehsil: 'Palghar',
    village: 'Manikpur',
    khataNumber: 'Khata-892',
    surveyGatNumber: '142/A-1',
    hissaNumber: 'Hissa-1',
    ulpin: 'ULPIN-MH-142A1-2026',
    totalLandAreaAcres: 3.45,
    acquiredAreaAcres: 2.45,
    retainedAreaAcres: 1.00,
    landClassification: 'Agricultural',
    soilType: 'Alluvial Loam / Fertile Coastal Plain',
    tenureType: 'Occupant Class I (Freehold Khatedar)',
    jointHolders: [
      { name: 'Smt. Anusaya D. Patil', shareFraction: '1/2', relation: 'Wife' },
      { name: 'Shri Rajesh D. Patil', shareFraction: '1/2', relation: 'Son' }
    ],
    initialPurchaseDate: '14/03/1988',
    initialPurchasePriceINR: 185000,
    lastAssessedCircleRateINR: 3620000,
    landOwnershipHistory: [
      {
        ownerName: 'Late Balaram Krishna Patil (Grandfather)',
        relationType: 'INHERITANCE',
        periodFrom: '1962',
        periodTo: '1988',
        transactionType: 'SUCCESSION_WARIS',
        deedRegistrationNo: 'MUT/PLG/1962/88',
        subRegistrarOffice: 'SRO Palghar Tahsil Office',
        considerationAmountINR: 0,
        areaTransferredAcres: 3.45,
        mutationEntryNo: '714',
        mutationApprovalDate: '22/08/1962',
        verifiedByTahsildar: 'Tehsildar Palghar',
      },
      {
        ownerName: 'Shri Dattatray B. Patil & Joint Family',
        relationType: 'SELF',
        periodFrom: '1988',
        periodTo: 'Present',
        transactionType: 'SALE_DEED',
        deedRegistrationNo: 'BHR-MH-88-00412',
        subRegistrarOffice: 'Joint SRO Class-1 Palghar',
        considerationAmountINR: 185000,
        areaTransferredAcres: 3.45,
        mutationEntryNo: '1429',
        mutationApprovalDate: '14/03/1988',
        verifiedByTahsildar: 'Sub-Divisional Officer (SDO)',
      },
      {
        ownerName: 'National Land Acquisition Authority (Statutory Award)',
        relationType: 'GOVERNMENT_ALLOTMENT',
        periodFrom: '2026',
        periodTo: 'Current Order',
        transactionType: 'ACQUISITION_NOTIFIED',
        deedRegistrationNo: 'GAZ/NHSRCL/SEC19/2026/04',
        subRegistrarOffice: 'Special Land Acquisition Officer (SLAO)',
        considerationAmountINR: 27500000,
        areaTransferredAcres: 2.45,
        mutationEntryNo: '9841',
        mutationApprovalDate: '18/01/2026',
        verifiedByTahsildar: 'Competent Authority & SLAO Palghar',
      }
    ],
    encumbrances: [
      {
        institutionName: 'State Bank of India (Palghar Agri Branch)',
        loanType: 'KCC_CROP_LOAN',
        chargeAmountINR: 250000,
        status: 'DISCHARGED',
        chargeDate: '12/06/2019',
        nocCertificateNo: 'SBI/NOC/AGR-2025-991',
      }
    ],
    estimatedValuationINR: 12500000,
    solatiumINR: 12500000,
    totalCompensationINR: 27500000,
    disbursementStatus: 'DISBURSED',
    bankDetails: {
      bankName: 'State Bank of India (Palghar Branch)',
      accountMasked: 'XXXXXX4092',
      ifsc: 'SBIN0001244',
    },
    dgpsPillars: [
      { pillarId: 'PIL-142-NW', lat: 19.6975, lng: 72.7690, rtkAccuracyCm: 1.4 },
      { pillarId: 'PIL-142-NE', lat: 19.6976, lng: 72.7710, rtkAccuracyCm: 1.2 },
      { pillarId: 'PIL-142-SE', lat: 19.6958, lng: 72.7712, rtkAccuracyCm: 1.6 },
      { pillarId: 'PIL-142-SW', lat: 19.6957, lng: 72.7691, rtkAccuracyCm: 1.3 },
    ],
    boundaryPolygon: [
      { lat: 19.6975, lng: 72.7690 },
      { lat: 19.6976, lng: 72.7710 },
      { lat: 19.6958, lng: 72.7712 },
      { lat: 19.6957, lng: 72.7691 },
    ],
    qrPasscode: 'QR-KS-MH-142A1',
    arVerificationStatus: 'VERIFIED',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isDeleted: false,
  },
  {
    id: 'farmer-palghar-002',
    farmerName: 'Smt. Shakuntala Ramdas Mhatre',
    contactNumber: '+91 97654 11209',
    aadhaarMasked: 'XXXX-XXXX-3419',
    state: 'Maharashtra',
    district: 'Palghar',
    talukaTehsil: 'Palghar',
    village: 'Kelve',
    khataNumber: 'Khata-104',
    surveyGatNumber: '143/2-B',
    hissaNumber: 'Hissa-2B',
    ulpin: 'ULPIN-MH-1432B-2026',
    totalLandAreaAcres: 4.10,
    acquiredAreaAcres: 3.10,
    retainedAreaAcres: 1.00,
    landClassification: 'Agricultural',
    soilType: 'Red Laterite Coastal Soil',
    tenureType: 'Occupant Class I (Ancestral Sole)',
    jointHolders: [
      { name: 'Shri Vinayak R. Mhatre', shareFraction: '1/1', relation: 'Son & Legal Heir' }
    ],
    initialPurchaseDate: '02/11/1995',
    initialPurchasePriceINR: 240000,
    lastAssessedCircleRateINR: 5000000,
    landOwnershipHistory: [
      {
        ownerName: 'Late Ramdas Ganpat Mhatre',
        relationType: 'PURCHASE',
        periodFrom: '1995',
        periodTo: '2018',
        transactionType: 'SALE_DEED',
        deedRegistrationNo: 'SRO/KEL/1995/1102',
        subRegistrarOffice: 'Sub-Registrar Kelve Road',
        considerationAmountINR: 240000,
        areaTransferredAcres: 4.10,
        mutationEntryNo: '1892',
        mutationApprovalDate: '02/11/1995',
        verifiedByTahsildar: 'Circle Inspector Kelve',
      },
      {
        ownerName: 'Smt. Shakuntala Ramdas Mhatre (Legal Waras)',
        relationType: 'INHERITANCE',
        periodFrom: '2018',
        periodTo: 'Present',
        transactionType: 'SUCCESSION_WARIS',
        deedRegistrationNo: 'WARAS-2018-0914',
        subRegistrarOffice: 'Talathi Office Kelve',
        considerationAmountINR: 0,
        areaTransferredAcres: 4.10,
        mutationEntryNo: '3104',
        mutationApprovalDate: '19/04/2018',
        verifiedByTahsildar: 'Naib Tehsildar Palghar',
      }
    ],
    encumbrances: [
      {
        institutionName: 'Bank of Baroda (Kelve Branch)',
        loanType: 'LAND_MORTGAGE',
        chargeAmountINR: 600000,
        status: 'ACTIVE',
        chargeDate: '10/08/2021',
      }
    ],
    estimatedValuationINR: 15500000,
    solatiumINR: 15500000,
    totalCompensationINR: 34100000,
    disbursementStatus: 'IN_PROGRESS',
    bankDetails: {
      bankName: 'Bank of Baroda (Kelve Road)',
      accountMasked: 'XXXXXX9823',
      ifsc: 'BARB0KELVEX',
    },
    dgpsPillars: [
      { pillarId: 'PIL-143-N', lat: 19.6212, lng: 72.7392, rtkAccuracyCm: 2.1 },
      { pillarId: 'PIL-143-E', lat: 19.6215, lng: 72.7415, rtkAccuracyCm: 2.4 },
      { pillarId: 'PIL-143-S', lat: 19.6190, lng: 72.7418, rtkAccuracyCm: 1.9 },
      { pillarId: 'PIL-143-W', lat: 19.6188, lng: 72.7390, rtkAccuracyCm: 2.0 },
    ],
    boundaryPolygon: [
      { lat: 19.6212, lng: 72.7392 },
      { lat: 19.6215, lng: 72.7415 },
      { lat: 19.6190, lng: 72.7418 },
      { lat: 19.6188, lng: 72.7390 },
    ],
    qrPasscode: 'QR-KS-MH-1432B',
    arVerificationStatus: 'FLAGGED_MISMATCH',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isDeleted: false,
  },
  {
    id: 'farmer-surat-003',
    farmerName: 'Shri Arvindbhai Shankarbhai Patel',
    contactNumber: '+91 98982 77610',
    aadhaarMasked: 'XXXX-XXXX-9901',
    state: 'Gujarat',
    district: 'Surat',
    talukaTehsil: 'Choryasi',
    village: 'Sachin',
    khataNumber: 'Khata-412',
    surveyGatNumber: '204/1',
    hissaNumber: 'Hissa-A',
    ulpin: 'ULPIN-GJ-2041A-2026',
    totalLandAreaAcres: 5.80,
    acquiredAreaAcres: 5.20,
    retainedAreaAcres: 0.60,
    landClassification: 'Agricultural',
    soilType: 'Black Cotton Heavy Clay Soil',
    tenureType: 'Occupant Class I (Freehold)',
    jointHolders: [
      { name: 'Shri Bhaveshbhai A. Patel', shareFraction: '1/2', relation: 'Son' },
      { name: 'Shri Hiteshbhai A. Patel', shareFraction: '1/2', relation: 'Son' }
    ],
    initialPurchaseDate: '10/01/2004',
    initialPurchasePriceINR: 1200000,
    lastAssessedCircleRateINR: 5960000,
    landOwnershipHistory: [
      {
        ownerName: 'Shri Shankarbhai N. Patel',
        relationType: 'PURCHASE',
        periodFrom: '2004',
        periodTo: '2016',
        transactionType: 'SALE_DEED',
        deedRegistrationNo: 'SR-SURAT-2004-883',
        subRegistrarOffice: 'SRO Choryasi Surat',
        considerationAmountINR: 1200000,
        areaTransferredAcres: 5.80,
        mutationEntryNo: '4412',
        mutationApprovalDate: '10/01/2004',
        verifiedByTahsildar: 'Mamlatdar Choryasi',
      },
      {
        ownerName: 'Shri Arvindbhai Shankarbhai Patel',
        relationType: 'INHERITANCE',
        periodFrom: '2016',
        periodTo: 'Present',
        transactionType: 'SUCCESSION_WARIS',
        deedRegistrationNo: 'WAR-SRT-2016-102',
        subRegistrarOffice: 'Mamlatdar Office Surat',
        considerationAmountINR: 0,
        areaTransferredAcres: 5.80,
        mutationEntryNo: '5819',
        mutationApprovalDate: '15/09/2016',
        verifiedByTahsildar: 'Deputy Mamlatdar Revenue',
      }
    ],
    encumbrances: [],
    estimatedValuationINR: 31000000,
    solatiumINR: 31000000,
    totalCompensationINR: 68200000,
    disbursementStatus: 'DISBURSED',
    bankDetails: {
      bankName: 'HDFC Bank (Surat Ring Road)',
      accountMasked: 'XXXXXX5512',
      ifsc: 'HDFC0000067',
    },
    dgpsPillars: [
      { pillarId: 'PIL-SRT-01', lat: 21.1710, lng: 72.8300, rtkAccuracyCm: 1.1 },
      { pillarId: 'PIL-SRT-02', lat: 21.1718, lng: 72.8335, rtkAccuracyCm: 0.9 },
      { pillarId: 'PIL-SRT-03', lat: 21.1690, lng: 72.8339, rtkAccuracyCm: 1.2 },
      { pillarId: 'PIL-SRT-04', lat: 21.1685, lng: 72.8305, rtkAccuracyCm: 1.0 },
    ],
    boundaryPolygon: [
      { lat: 21.1710, lng: 72.8300 },
      { lat: 21.1718, lng: 72.8335 },
      { lat: 21.1690, lng: 72.8339 },
      { lat: 21.1685, lng: 72.8305 },
    ],
    qrPasscode: 'QR-KS-GJ-2041A',
    arVerificationStatus: 'VERIFIED',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isDeleted: false,
  },
  {
    id: 'farmer-jaipur-004',
    farmerName: 'Shri Jagdishprasad R. Sharma',
    contactNumber: '+91 94140 22891',
    aadhaarMasked: 'XXXX-XXXX-6612',
    state: 'Rajasthan',
    district: 'Jaipur',
    talukaTehsil: 'Bassi',
    village: 'Bassi Rural',
    khataNumber: 'Khata-771',
    surveyGatNumber: '119/2',
    hissaNumber: 'Hissa-3',
    ulpin: 'ULPIN-RJ-1192J-2026',
    totalLandAreaAcres: 6.20,
    acquiredAreaAcres: 5.10,
    retainedAreaAcres: 1.10,
    landClassification: 'Agricultural',
    soilType: 'Sandy Loam Semiarid Soil',
    tenureType: 'Khatedar Tenant (Permanent)',
    jointHolders: [
      { name: 'Smt. Murti Devi Sharma', shareFraction: '1/3', relation: 'Wife' },
      { name: 'Shri Mukesh Sharma', shareFraction: '2/3', relation: 'Son' }
    ],
    initialPurchaseDate: '18/04/1985',
    initialPurchasePriceINR: 110000,
    lastAssessedCircleRateINR: 3800000,
    landOwnershipHistory: [
      {
        ownerName: 'Late Chhitar Mal Sharma',
        relationType: 'INHERITANCE',
        periodFrom: '1960',
        periodTo: '1985',
        transactionType: 'SUCCESSION_WARIS',
        deedRegistrationNo: 'RJ-CHK-1960-12',
        subRegistrarOffice: 'SRO Bassi Jaipur',
        considerationAmountINR: 0,
        areaTransferredAcres: 6.20,
        mutationEntryNo: '312',
        mutationApprovalDate: '01/03/1960',
        verifiedByTahsildar: 'Tehsildar Bassi',
      },
      {
        ownerName: 'Shri Jagdishprasad R. Sharma',
        relationType: 'SELF',
        periodFrom: '1985',
        periodTo: 'Present',
        transactionType: 'SALE_DEED',
        deedRegistrationNo: 'REG-BAS-1985-99',
        subRegistrarOffice: 'Tehsil Bassi Sub-Registrar',
        considerationAmountINR: 110000,
        areaTransferredAcres: 6.20,
        mutationEntryNo: '945',
        mutationApprovalDate: '18/04/1985',
        verifiedByTahsildar: 'SDO Bassi',
      }
    ],
    encumbrances: [],
    estimatedValuationINR: 19000000,
    solatiumINR: 19000000,
    totalCompensationINR: 41800000,
    disbursementStatus: 'DISBURSED',
    bankDetails: {
      bankName: 'Punjab National Bank (Jaipur Bassi)',
      accountMasked: 'XXXXXX1902',
      ifsc: 'PUNB0024400',
    },
    dgpsPillars: [
      { pillarId: 'PIL-JPR-01', lat: 26.8915, lng: 76.3285, rtkAccuracyCm: 1.5 },
      { pillarId: 'PIL-JPR-02', lat: 26.8920, lng: 76.3325, rtkAccuracyCm: 1.3 },
      { pillarId: 'PIL-JPR-03', lat: 26.8885, lng: 76.3330, rtkAccuracyCm: 1.7 },
      { pillarId: 'PIL-JPR-04', lat: 26.8880, lng: 76.3288, rtkAccuracyCm: 1.4 },
    ],
    boundaryPolygon: [
      { lat: 26.8915, lng: 76.3285 },
      { lat: 26.8920, lng: 76.3325 },
      { lat: 26.8885, lng: 76.3330 },
      { lat: 26.8880, lng: 76.3288 },
    ],
    qrPasscode: 'QR-KS-RJ-1192J',
    arVerificationStatus: 'VERIFIED',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isDeleted: false,
  },
  {
    id: 'farmer-varanasi-005',
    farmerName: 'Shri Ramakant S. Mishra',
    contactNumber: '+91 94500 88231',
    aadhaarMasked: 'XXXX-XXXX-1144',
    state: 'Uttar Pradesh',
    district: 'Varanasi',
    talukaTehsil: 'Pindra',
    village: 'Rohania',
    khataNumber: 'Khata-512',
    surveyGatNumber: '881/P-4',
    hissaNumber: 'Hissa-4',
    ulpin: 'ULPIN-UP-881P4-2026',
    totalLandAreaAcres: 4.50,
    acquiredAreaAcres: 4.20,
    retainedAreaAcres: 0.30,
    landClassification: 'Agricultural',
    soilType: 'Gangetic Alluvial Silt Soil',
    tenureType: 'Bhumidhar with Transferable Rights',
    jointHolders: [
      { name: 'Shri Govind R. Mishra', shareFraction: '1/2', relation: 'Brother' },
      { name: 'Shri Shyam R. Mishra', shareFraction: '1/2', relation: 'Brother' }
    ],
    initialPurchaseDate: '12/08/1979',
    initialPurchasePriceINR: 95000,
    lastAssessedCircleRateINR: 3900000,
    landOwnershipHistory: [
      {
        ownerName: 'Late Pt. Sitaram Mishra (Father)',
        relationType: 'INHERITANCE',
        periodFrom: '1958',
        periodTo: '1979',
        transactionType: 'SUCCESSION_WARIS',
        deedRegistrationNo: 'UP-VNS-1958-002',
        subRegistrarOffice: 'Tehsil Pindra SRO',
        considerationAmountINR: 0,
        areaTransferredAcres: 4.50,
        mutationEntryNo: '102',
        mutationApprovalDate: '04/05/1958',
        verifiedByTahsildar: 'Tehsildar Pindra',
      },
      {
        ownerName: 'Shri Ramakant Mishra & Brothers',
        relationType: 'PARTITION',
        periodFrom: '1979',
        periodTo: 'Present',
        transactionType: 'PARTITION',
        deedRegistrationNo: 'PART-VNS-1979-45',
        subRegistrarOffice: 'Sub-Registrar Pindra',
        considerationAmountINR: 95000,
        areaTransferredAcres: 4.50,
        mutationEntryNo: '489',
        mutationApprovalDate: '12/08/1979',
        verifiedByTahsildar: 'SDM Pindra',
      }
    ],
    encumbrances: [
      {
        institutionName: 'Union Bank of India (Varanasi)',
        loanType: 'KCC_CROP_LOAN',
        chargeAmountINR: 200000,
        status: 'DISCHARGED',
        chargeDate: '05/03/2018',
        nocCertificateNo: 'UBI/VNS/NOC-2023-118',
      }
    ],
    estimatedValuationINR: 16000000,
    solatiumINR: 16000000,
    totalCompensationINR: 35200000,
    disbursementStatus: 'IN_PROGRESS',
    bankDetails: {
      bankName: 'Union Bank of India (Varanasi Cantonment)',
      accountMasked: 'XXXXXX7732',
      ifsc: 'UBIN0530182',
    },
    dgpsPillars: [
      { pillarId: 'PIL-VNS-01', lat: 25.3188, lng: 82.9715, rtkAccuracyCm: 1.8 },
      { pillarId: 'PIL-VNS-02', lat: 25.3195, lng: 82.9755, rtkAccuracyCm: 1.4 },
      { pillarId: 'PIL-VNS-03', lat: 25.3160, lng: 82.9760, rtkAccuracyCm: 1.9 },
      { pillarId: 'PIL-VNS-04', lat: 25.3155, lng: 82.9718, rtkAccuracyCm: 1.6 },
    ],
    boundaryPolygon: [
      { lat: 25.3188, lng: 82.9715 },
      { lat: 25.3195, lng: 82.9755 },
      { lat: 25.3160, lng: 82.9760 },
      { lat: 25.3155, lng: 82.9718 },
    ],
    qrPasscode: 'QR-KS-UP-881P4',
    arVerificationStatus: 'PENDING_VISIT',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isDeleted: false,
  },
  {
    id: 'farmer-prayagraj-006',
    farmerName: 'Smt. Kaushalya Devi Yadav',
    contactNumber: '+91 94152 66718',
    aadhaarMasked: 'XXXX-XXXX-4523',
    state: 'Uttar Pradesh',
    district: 'Prayagraj',
    talukaTehsil: 'Soraon',
    village: 'Mau Aima',
    khataNumber: 'Khata-328',
    surveyGatNumber: '415/2',
    hissaNumber: 'Hissa-2',
    ulpin: 'ULPIN-UP-4152P-2026',
    totalLandAreaAcres: 4.80,
    acquiredAreaAcres: 4.10,
    retainedAreaAcres: 0.70,
    landClassification: 'Agricultural',
    soilType: 'Doab Alluvial Deep Soil',
    tenureType: 'Bhumidhar with Transferable Rights',
    jointHolders: [
      { name: 'Shri Akhilesh Yadav', shareFraction: '1/2', relation: 'Son' },
      { name: 'Smt. Sarita Yadav', shareFraction: '1/2', relation: 'Daughter-in-law' }
    ],
    initialPurchaseDate: '20/09/2001',
    initialPurchasePriceINR: 520000,
    lastAssessedCircleRateINR: 4100000,
    landOwnershipHistory: [
      {
        ownerName: 'Shri Ramswaroop Yadav',
        relationType: 'PURCHASE',
        periodFrom: '2001',
        periodTo: '2019',
        transactionType: 'SALE_DEED',
        deedRegistrationNo: 'SRO-SORAON-2001-309',
        subRegistrarOffice: 'SRO Soraon Prayagraj',
        considerationAmountINR: 520000,
        areaTransferredAcres: 4.80,
        mutationEntryNo: '1410',
        mutationApprovalDate: '20/09/2001',
        verifiedByTahsildar: 'Tehsildar Soraon',
      },
      {
        ownerName: 'Smt. Kaushalya Devi Yadav',
        relationType: 'INHERITANCE',
        periodFrom: '2019',
        periodTo: 'Present',
        transactionType: 'SUCCESSION_WARIS',
        deedRegistrationNo: 'WARAS-PRY-2019-92',
        subRegistrarOffice: 'Tehsil Soraon Office',
        considerationAmountINR: 0,
        areaTransferredAcres: 4.80,
        mutationEntryNo: '2890',
        mutationApprovalDate: '11/02/2019',
        verifiedByTahsildar: 'Naib Tehsildar Soraon',
      }
    ],
    encumbrances: [],
    estimatedValuationINR: 18000000,
    solatiumINR: 18000000,
    totalCompensationINR: 39600000,
    disbursementStatus: 'PENDING',
    bankDetails: {
      bankName: 'Indian Bank (Civil Lines Prayagraj)',
      accountMasked: 'XXXXXX8819',
      ifsc: 'IDIB000C028',
    },
    dgpsPillars: [
      { pillarId: 'PIL-PRY-01', lat: 25.4370, lng: 81.8445, rtkAccuracyCm: 1.5 },
      { pillarId: 'PIL-PRY-02', lat: 25.4378, lng: 81.8480, rtkAccuracyCm: 1.2 },
      { pillarId: 'PIL-PRY-03', lat: 25.4345, lng: 81.8485, rtkAccuracyCm: 1.7 },
      { pillarId: 'PIL-PRY-04', lat: 25.4340, lng: 81.8448, rtkAccuracyCm: 1.3 },
    ],
    boundaryPolygon: [
      { lat: 25.4370, lng: 81.8445 },
      { lat: 25.4378, lng: 81.8480 },
      { lat: 25.4345, lng: 81.8485 },
      { lat: 25.4340, lng: 81.8448 },
    ],
    qrPasscode: 'QR-KS-UP-4152P',
    arVerificationStatus: 'VERIFIED',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isDeleted: false,
  },
  {
    id: 'farmer-thane-007',
    farmerName: 'Shri Nilesh Jayant Deshmukh',
    contactNumber: '+91 98201 33499',
    aadhaarMasked: 'XXXX-XXXX-7788',
    state: 'Maharashtra',
    district: 'Thane',
    talukaTehsil: 'Bhiwandi',
    village: 'Anjur',
    khataNumber: 'Khata-602',
    surveyGatNumber: '512/3',
    hissaNumber: 'Hissa-3',
    ulpin: 'ULPIN-MH-5123THN-2026',
    totalLandAreaAcres: 3.20,
    acquiredAreaAcres: 2.10,
    retainedAreaAcres: 1.10,
    landClassification: 'Residential',
    soilType: 'Coastal Clay Urban Fringe',
    tenureType: 'Occupant Class I (NA Converted)',
    jointHolders: [
      { name: 'Smt. Priya N. Deshmukh', shareFraction: '1/2', relation: 'Wife' },
      { name: 'Shri Jayant S. Deshmukh', shareFraction: '1/2', relation: 'Father' }
    ],
    initialPurchaseDate: '15/06/1991',
    initialPurchasePriceINR: 150000,
    lastAssessedCircleRateINR: 6870000,
    landOwnershipHistory: [
      {
        ownerName: 'Shri Jayant S. Deshmukh',
        relationType: 'PURCHASE',
        periodFrom: '1991',
        periodTo: '2012',
        transactionType: 'SALE_DEED',
        deedRegistrationNo: 'SRO/BHIWANDI/1991/44',
        subRegistrarOffice: 'SRO Bhiwandi Thane',
        considerationAmountINR: 150000,
        areaTransferredAcres: 3.20,
        mutationEntryNo: '882',
        mutationApprovalDate: '15/06/1991',
        verifiedByTahsildar: 'Mamlatdar Bhiwandi',
      },
      {
        ownerName: 'Shri Nilesh Jayant Deshmukh',
        relationType: 'INHERITANCE',
        periodFrom: '2012',
        periodTo: 'Present',
        transactionType: 'SUCCESSION_WARIS',
        deedRegistrationNo: 'DEED-WARAS-2012-78',
        subRegistrarOffice: 'Bhiwandi Sub-District Office',
        considerationAmountINR: 0,
        areaTransferredAcres: 3.20,
        mutationEntryNo: '1640',
        mutationApprovalDate: '24/11/2012',
        verifiedByTahsildar: 'Talathi Anjur',
      }
    ],
    encumbrances: [
      {
        institutionName: 'ICICI Bank Home Finance',
        loanType: 'LAND_MORTGAGE',
        chargeAmountINR: 1200000,
        status: 'ACTIVE',
        chargeDate: '14/02/2022',
      }
    ],
    estimatedValuationINR: 22000000,
    solatiumINR: 22000000,
    totalCompensationINR: 48400000,
    disbursementStatus: 'UNDER_DISPUTE',
    bankDetails: {
      bankName: 'ICICI Bank (Thane West)',
      accountMasked: 'XXXXXX6641',
      ifsc: 'ICIC0000102',
    },
    dgpsPillars: [
      { pillarId: 'PIL-THN-01', lat: 19.2195, lng: 72.9760, rtkAccuracyCm: 1.3 },
      { pillarId: 'PIL-THN-02', lat: 19.2202, lng: 72.9798, rtkAccuracyCm: 1.1 },
      { pillarId: 'PIL-THN-03', lat: 19.2170, lng: 72.9802, rtkAccuracyCm: 1.5 },
      { pillarId: 'PIL-THN-04', lat: 19.2165, lng: 72.9765, rtkAccuracyCm: 1.4 },
    ],
    boundaryPolygon: [
      { lat: 19.2195, lng: 72.9760 },
      { lat: 19.2202, lng: 72.9798 },
      { lat: 19.2170, lng: 72.9802 },
      { lat: 19.2165, lng: 72.9765 },
    ],
    qrPasscode: 'QR-KS-MH-5123T',
    arVerificationStatus: 'FLAGGED_MISMATCH',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isDeleted: false,
  },
  {
    id: 'farmer-vadodara-008',
    farmerName: 'Shri Mansukhbhai Gordhanbhai Vaghela',
    contactNumber: '+91 98791 55204',
    aadhaarMasked: 'XXXX-XXXX-2233',
    state: 'Gujarat',
    district: 'Vadodara',
    talukaTehsil: 'Karjan',
    village: 'Karjan Rural',
    khataNumber: 'Khata-994',
    surveyGatNumber: '312/1',
    hissaNumber: 'Hissa-1',
    ulpin: 'ULPIN-GJ-3121V-2026',
    totalLandAreaAcres: 5.10,
    acquiredAreaAcres: 4.60,
    retainedAreaAcres: 0.50,
    landClassification: 'Agricultural',
    soilType: 'Mahi River Alluvium Medium Black Soil',
    tenureType: 'Occupant Class I (Freehold)',
    jointHolders: [
      { name: 'Shri Kiritbhai M. Vaghela', shareFraction: '1/2', relation: 'Son' },
      { name: 'Shri Sanjaybhai M. Vaghela', shareFraction: '1/2', relation: 'Son' }
    ],
    initialPurchaseDate: '08/07/2010',
    initialPurchasePriceINR: 4500000,
    lastAssessedCircleRateINR: 6200000,
    landOwnershipHistory: [
      {
        ownerName: 'Shri Gordhanbhai Vaghela',
        relationType: 'PURCHASE',
        periodFrom: '2010',
        periodTo: '2021',
        transactionType: 'SALE_DEED',
        deedRegistrationNo: 'SRO-KARJAN-2010-912',
        subRegistrarOffice: 'SRO Karjan Vadodara',
        considerationAmountINR: 4500000,
        areaTransferredAcres: 5.10,
        mutationEntryNo: '5190',
        mutationApprovalDate: '08/07/2010',
        verifiedByTahsildar: 'Mamlatdar Karjan',
      },
      {
        ownerName: 'Shri Mansukhbhai Gordhanbhai Vaghela',
        relationType: 'GIFT_DEED',
        periodFrom: '2021',
        periodTo: 'Present',
        transactionType: 'GIFT',
        deedRegistrationNo: 'GIFT-VAD-2021-04',
        subRegistrarOffice: 'Sub-Registrar Karjan',
        considerationAmountINR: 0,
        areaTransferredAcres: 5.10,
        mutationEntryNo: '7218',
        mutationApprovalDate: '14/11/2021',
        verifiedByTahsildar: 'Talati-cum-Mantri Karjan',
      }
    ],
    encumbrances: [],
    estimatedValuationINR: 24000000,
    solatiumINR: 24000000,
    totalCompensationINR: 52800000,
    disbursementStatus: 'DISBURSED',
    bankDetails: {
      bankName: 'State Bank of India (Karjan)',
      accountMasked: 'XXXXXX3319',
      ifsc: 'SBIN0000401',
    },
    dgpsPillars: [
      { pillarId: 'PIL-VAD-01', lat: 22.3085, lng: 73.1795, rtkAccuracyCm: 1.0 },
      { pillarId: 'PIL-VAD-02', lat: 22.3092, lng: 73.1830, rtkAccuracyCm: 0.8 },
      { pillarId: 'PIL-VAD-03', lat: 22.3058, lng: 73.1835, rtkAccuracyCm: 1.2 },
      { pillarId: 'PIL-VAD-04', lat: 22.3052, lng: 73.1800, rtkAccuracyCm: 1.1 },
    ],
    boundaryPolygon: [
      { lat: 22.3085, lng: 73.1795 },
      { lat: 22.3092, lng: 73.1830 },
      { lat: 22.3058, lng: 73.1835 },
      { lat: 22.3052, lng: 73.1800 },
    ],
    qrPasscode: 'QR-KS-GJ-3121V',
    arVerificationStatus: 'VERIFIED',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isDeleted: false,
  },
  {
    id: 'farmer-kanpur-009',
    farmerName: 'Shri Suresh Chandra Verma',
    contactNumber: '+91 94150 99412',
    aadhaarMasked: 'XXXX-XXXX-5561',
    state: 'Uttar Pradesh',
    district: 'Kanpur Nagar',
    talukaTehsil: 'Bilhaur',
    village: 'Araul',
    khataNumber: 'Khata-817',
    surveyGatNumber: '712/4',
    hissaNumber: 'Hissa-4',
    ulpin: 'ULPIN-UP-7124K-2026',
    totalLandAreaAcres: 5.60,
    acquiredAreaAcres: 5.60,
    retainedAreaAcres: 0.00,
    landClassification: 'Commercial',
    soilType: 'Heavy Alluvial Plain with Highway Frontage',
    tenureType: 'Bhumidhar with Transferable Rights',
    jointHolders: [
      { name: 'Smt. Shanti Devi Verma', shareFraction: '1/1', relation: 'Wife' }
    ],
    initialPurchaseDate: '12/03/1998',
    initialPurchasePriceINR: 680000,
    lastAssessedCircleRateINR: 5710000,
    landOwnershipHistory: [
      {
        ownerName: 'Shri Babu Lal Verma',
        relationType: 'PURCHASE',
        periodFrom: '1998',
        periodTo: '2015',
        transactionType: 'SALE_DEED',
        deedRegistrationNo: 'SRO-BILHAUR-1998-12',
        subRegistrarOffice: 'SRO Bilhaur Kanpur',
        considerationAmountINR: 680000,
        areaTransferredAcres: 5.60,
        mutationEntryNo: '1902',
        mutationApprovalDate: '12/03/1998',
        verifiedByTahsildar: 'Tehsildar Bilhaur',
      },
      {
        ownerName: 'Shri Suresh Chandra Verma',
        relationType: 'INHERITANCE',
        periodFrom: '2015',
        periodTo: 'Present',
        transactionType: 'SUCCESSION_WARIS',
        deedRegistrationNo: 'WARAS-KNP-2015-81',
        subRegistrarOffice: 'Tehsil Bilhaur Office',
        considerationAmountINR: 0,
        areaTransferredAcres: 5.60,
        mutationEntryNo: '3711',
        mutationApprovalDate: '19/08/2015',
        verifiedByTahsildar: 'Sub-Divisional Magistrate (SDM)',
      }
    ],
    encumbrances: [],
    estimatedValuationINR: 32000000,
    solatiumINR: 32000000,
    totalCompensationINR: 70400000,
    disbursementStatus: 'IN_PROGRESS',
    bankDetails: {
      bankName: 'Canara Bank (Mall Road Kanpur)',
      accountMasked: 'XXXXXX1248',
      ifsc: 'CNRB0000219',
    },
    dgpsPillars: [
      { pillarId: 'PIL-KNP-01', lat: 26.4515, lng: 80.3300, rtkAccuracyCm: 1.4 },
      { pillarId: 'PIL-KNP-02', lat: 26.4522, lng: 80.3340, rtkAccuracyCm: 1.3 },
      { pillarId: 'PIL-KNP-03', lat: 26.4485, lng: 80.3345, rtkAccuracyCm: 1.6 },
      { pillarId: 'PIL-KNP-04', lat: 26.4480, lng: 80.3305, rtkAccuracyCm: 1.5 },
    ],
    boundaryPolygon: [
      { lat: 26.4515, lng: 80.3300 },
      { lat: 26.4522, lng: 80.3340 },
      { lat: 26.4485, lng: 80.3345 },
      { lat: 26.4480, lng: 80.3305 },
    ],
    qrPasscode: 'QR-KS-UP-7124K',
    arVerificationStatus: 'VERIFIED',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isDeleted: false,
  },
  {
    id: 'farmer-palghar-010',
    farmerName: 'Smt. Parvatibai Tukaram Gavit',
    contactNumber: '+91 97633 44018',
    aadhaarMasked: 'XXXX-XXXX-9045',
    state: 'Maharashtra',
    district: 'Palghar',
    talukaTehsil: 'Palghar',
    village: 'Umroli Tribal Circle',
    khataNumber: 'Khata-219',
    surveyGatNumber: '98/3',
    hissaNumber: 'Hissa-3',
    ulpin: 'ULPIN-MH-983UM-2026',
    totalLandAreaAcres: 3.75,
    acquiredAreaAcres: 3.75,
    retainedAreaAcres: 0.00,
    landClassification: 'Agricultural',
    soilType: 'Forest Fringe Gravelly Loam',
    tenureType: 'Occupant Class II (Forest Rights Act Title Holder)',
    jointHolders: [
      { name: 'Shri Hiraman T. Gavit', shareFraction: '1/2', relation: 'Son' },
      { name: 'Smt. Sitabai T. Gavit', shareFraction: '1/2', relation: 'Daughter' }
    ],
    initialPurchaseDate: '26/01/2008',
    initialPurchasePriceINR: 0,
    lastAssessedCircleRateINR: 2930000,
    landOwnershipHistory: [
      {
        ownerName: 'Tribal Ancestral Lineage (Govt Allotment under FRA)',
        relationType: 'GOVERNMENT_ALLOTMENT',
        periodFrom: '2008',
        periodTo: '2016',
        transactionType: 'SALE_DEED',
        deedRegistrationNo: 'FRA-PATTA-2008-019',
        subRegistrarOffice: 'District Collector Office Palghar',
        considerationAmountINR: 0,
        areaTransferredAcres: 3.75,
        mutationEntryNo: '718',
        mutationApprovalDate: '26/01/2008',
        verifiedByTahsildar: 'Collector Palghar',
      },
      {
        ownerName: 'Smt. Parvatibai Tukaram Gavit',
        relationType: 'INHERITANCE',
        periodFrom: '2016',
        periodTo: 'Present',
        transactionType: 'SUCCESSION_WARIS',
        deedRegistrationNo: 'WARAS-UMR-2016-44',
        subRegistrarOffice: 'Talathi Office Umroli',
        considerationAmountINR: 0,
        areaTransferredAcres: 3.75,
        mutationEntryNo: '1105',
        mutationApprovalDate: '09/06/2016',
        verifiedByTahsildar: 'Naib Tehsildar Tribal Cell',
      }
    ],
    encumbrances: [],
    estimatedValuationINR: 11000000,
    solatiumINR: 11000000,
    totalCompensationINR: 24200000,
    disbursementStatus: 'DISBURSED',
    bankDetails: {
      bankName: 'Thane District Central Co-op Bank (Umroli)',
      accountMasked: 'XXXXXX5011',
      ifsc: 'TDCB0000042',
    },
    dgpsPillars: [
      { pillarId: 'PIL-UMR-01', lat: 19.6820, lng: 72.7510, rtkAccuracyCm: 1.7 },
      { pillarId: 'PIL-UMR-02', lat: 19.6828, lng: 72.7545, rtkAccuracyCm: 1.5 },
      { pillarId: 'PIL-UMR-03', lat: 19.6795, lng: 72.7550, rtkAccuracyCm: 1.8 },
      { pillarId: 'PIL-UMR-04', lat: 19.6790, lng: 72.7515, rtkAccuracyCm: 1.6 },
    ],
    boundaryPolygon: [
      { lat: 19.6820, lng: 72.7510 },
      { lat: 19.6828, lng: 72.7545 },
      { lat: 19.6795, lng: 72.7550 },
      { lat: 19.6790, lng: 72.7515 },
    ],
    qrPasscode: 'QR-KS-MH-983UM',
    arVerificationStatus: 'VERIFIED',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isDeleted: false,
  }
];

async function runSeed() {
  console.log('Writing 10 farmer records directly to Firestore...');
  for (const f of farmers) {
    const docRef = doc(db, 'farmers', f.id);
    await setDoc(docRef, f);
    console.log('Seeded:', f.farmerName, '(' + f.id + ')');
  }
  console.log('All 10 farmers successfully seeded into Firestore collection `farmers`!');
  process.exit(0);
}

runSeed().catch((err) => {
  console.error('Error seeding farmers:', err);
  process.exit(1);
});
